---
- name: restore playbook.yml
  hosts: all
  tasks:
    - name: 방화벽 내리기 - dns
      firewalld:
        service: dns
        permanent: yes
        immediate: yes
        state: disabled
    
    - name: 서비스 내리기 - named, firewalld
      service:
        name: "{{ item  }}"
        state: stopped
      with_items:
        - named
        - firewalld
    
    - name: 패키지 삭제 - bind, bind-utils, firewalld
      yum:
        name: 
          - bind
          - bind-utils
          - firewalld
        state: absent
    

    - name: 디렉토리 지우기 - /var/named
      file:
        path: /var/named
        state: directory


