---
- name: restore playbook.yml
  hosts: web1
  tasks: 
    - name: 변수 포함
      include_vars: vars/main.yml

    # 1) 방화벽 닫기 - httpd
    - name: 1) 방화벽 닫기 - http
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled
      ignore_errors: yes

    # 2) 서비스 내리기 - firewalld, httpd
    - name: 2) 서비스 내리기 - firewalld
      service: 
        name: "{{ item }}"
        state: stopped
      loop:
          - firewalld
          - httpd

    # 3) 웹서비스 설정 삭제
    # * /var/www/html/index.html
    - name: /var/www/html/index.html 삭제
      file: 
        path: "{{ web_root }}/index.html"
        state: absent

    # 4) 패키지 삭제 - httpd, firewalld
    - name: 4) 패키지 삭제 - httpd, firewalld
      yum: 
        name:
          - httpd
          - firewalld
        state: absent

    # 5) 팩트 삭제 - /etc/ansible/facts.d
    - name: 5) 팩트 삭제 - /etc/ansible/facts.d    
      file:
        path: /etc/ansible/facts.d
        state: absent