---
- name: restore playbook.yml
  hosts: all
  gather_facts: yes
  vars_files: vars.yml
  tasks:
    # 1) 방화벽 내리기 - http, https
    # 2) 파일 시스템 삭제 - /var/www/html/index.html
    # 3) 웹서비스 삭제
    #   * files/localhost.key -> /etc/pki/tls/private/localhost.key
    #   * files/localhost.crt -> /etc/pki/tls/private/localhost.crt
    # 4) 서비스 내리기 - httpd, firewalld
    # 5) 패키지 삭제 - httpd, mod_ssl, firewalld


    # 1) 방화벽 내리기 - http, https
    - name: 1) 방화벽 내리기 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      with_items: "{{ fw_svcs }}"

    # 2) 파일 시스템 삭제 - /var/www/html/index.html
    - name: 2) 파일 시스템 삭제 - /var/www/html/index.html
      file: 
        path: "{{ index_dest }}"
        state: absent

    # 3) 웹서비스 삭제
    #   * files/localhost.key -> /etc/pki/tls/private/localhost.key
    #   * files/localhost.crt -> /etc/pki/tls/private/localhost.crt
    - name: 3) 웹서비스 삭제
      file: 
        path: "{{ item.dest }}"
        state: absent
      with_items: "{{ tls_cert_files }}"

    # 4) 서비스 내리기 - httpd, firewalld
    - name: 4) 서비스 내리기 - httpd, firewalld
      service: 
        name: "{{ item }}"
        state: stopped
      with_items: "{{ services }}"

    # 5) 패키지 삭제 - httpd, mod_ssl, firewalld
    - name: 5) 패키지 삭제 - httpd, mod_ssl, firewalld
      yum: 
        name: "{{ item }}"
        state: absent
      with_items: "{{ packages }}"
    