---
- name: restore the site.yml
  hosts: webservers
  tasks:
    # (1) firewalld -http, https 내리기
    # (2) service -httpd 내리기
    # (3) /var/www/htnl/index.html
    # (4) httpd, mod_ssl 패키지 삭제
    - name: (1) 방화벽 서비스 내리기 - http, https
      firewalld: 
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
      - http
      - https
    - name: (2) 웹서비스 내리기 - httpd
      service: 
        name:  httpd
        state: stopped
        enabled: no
    - name: (3) /var/www/html/index.html 파일 지우기
      file:  
        path: /var/www/html/index.html
        state: absent
    - name: (4) 패키지 삭제 - httpd, mod_ssl
      yum:
        name:
          - httpd
          - mod_ssl
        state: absent
      
        