--- 
- name: ansible4 LVM 구성
  hosts: webserver
  vars:
    lvms:
      - { lvname: lv1, lvsize: 500M }
      - { lvname: lv2, lvsize: 1G }
    mounts:
      - { mountdir: /lv1, device: /dev/vg1/lv1, fstype: ext4 }
      - { mountdir: /lv2, device: /dev/vg1/lv2, fstype: xfs }
  tasks:
    # 1) 파티션 작업 - /dev/sdb1(1G), /dev/sdc1(1G)
    # 2) LVM 작업 
    # 2-1) PV(/dev/sdb1, /dev/sdc1) --> VG 구성(vg1)
    # 2-2) VG(/dev/vg1) -> LV 구성(lv1(50M), lv2(1G))
    # 3) FS 작업
    # 3-1) /dev/vg1/lv1 - ext4 ->
    # 3-2) /dev/vg1/lv2 - xfs ->
    # 4) 마운트 작업 -  /etc/fstab
    # 4-1) /dev/vg1/lv1(ext4) --> /mnt/lv1
    # 4-2) /dev/vg1/lv2(xfs) --> /mnt/lv2


    # 1) 파티션 작업 - /dev/sdb1(1G), /dev/sdc1(1G)
    - name: 1) 파티션 작업 - /dev/sdb1(1G), /dev/sdc1(1G)
      community.general.parted:
        device: "{{ item }}"
        number: 1
        state: present
        part_end: 100%
      with_items:
        - /dev/sdb
        - /dev/sdc

    # 2) LVM 작업 
    # 2-1) PV(/dev/sdb1, /dev/sdc1) --> VG 구성(vg1)
    - name: 2-1) PV(/dev/sdb1, /dev/sdc1) --> VG 구성(vg1)
      community.general.lvg:
        vg: vg1
        pvs: /dev/sdb1,/dev/sdc1
   
    # 2-2) VG(/dev/vg1) -> LV 구성(lv1(500M), lv2(1G))
    - name: 2-2-1) VG(/dev/vg1) -> LV 구성(lv1(500M)
      community.general.lvol:
        vg: /dev/vg1
        lv: "{{ item.lvname }}"
        size: "{{ item.lvsize }}"
      with_items: "{{ lvms }}"
  
    # 3) FS 작업
    # 3-1) /dev/vg1/lv1 - ext4 ->
    - name: 3-1) /dev/vg1/lv1 - ext4 ->
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vg1/lv1
      
    # 3-2) /dev/vg1/lv2 - xfs ->
    - name: 3-2) /dev/vg1/lv2 - xfs ->
      community.general.filesystem:
        fstype: xfs
        dev: /dev/vg1/lv2

    # 4) 마운트 작업 -  /etc/fstab
    # 4-1) /dev/vg1/lv1(ext4) --> /mnt/lv1
    - name: 4-1) /dev/vg1/lv1(ext4) --> /mnt/lv1
      ansible.posix.mount:
        path: "{{ item.mountdir }}"
        src: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        state: mounted
      with_items: "{{ mounts }}"


    # # 4-2) /dev/vg1/lv2(xfs) --> /mnt/lv2
    # - name: 4-2) /dev/vg1/lv2(xfs) --> /mnt/lv2
    #   ansible.posix.mount:
    #     path: /mnt/lv2
    #     src: /dev/vg1/lv2
    #     fstype: xfs
    #     state: mounted